command:
  - node
  - dist/index.js

env:
  - name: PORT
    value: "8000"
  - name: DATABRICKS_WAREHOUSE_ID
    value: "87e069097741b56c"
  - name: UC_SCHEMA
    value: "oil_pump_monitor_catalog.production_optimizer"
